Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: "trailing"

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 50

Metrics/ModuleLength:
  Max: 250

Naming/HeredocDelimiterNaming:
  Enabled: false

Performance/RedundantMatch:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Security/Open:
  Exclude:
    - "tools/get_assets.rb"

Metrics/LineLength:
  Max: 120
  Exclude:
    - "smalruby3.gemspec"

Layout/ExtraSpacing:
  Exclude:
    - "smalruby3.gemspec"

Layout/SpaceAroundOperators:
  Exclude:
    - "smalruby3.gemspec"

Style/UnneededPercentQ:
  Exclude:
    - "smalruby3.gemspec"

Style/SpecialGlobalVars:
  Exclude:
    - "smalruby3.gemspec"

Style/ExpandPathArguments:
  Exclude:
    - "smalruby3.gemspec"
    - "spec/spec_helper.rb"

Layout/AlignParameters:
  Exclude:
    - 'examples/*'

Style/GlobalVars:
  Exclude:
    - 'examples/*'
    - 'spec/**/*'

Style/WordArray:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
